---
name: LLVM Tests

on:
  workflow_dispatch:
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  DEV_IMAGE: ghcr.io/gaia-platform/dev-base-gaia-platform:latest

jobs:

  Coverage:
    runs-on: ubuntu-20.04
    env:
      GAIA_REPO: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Action
        uses: ./.github/actions/setup-job

      - name: Coverage
        uses: ./.github/actions/coverage-job
        with:
          gaia-repo: ${{ github.workspace }}
          job-name: ${{ github.job }}
